---
hostname: rt-cisco-1

bgp:
  bgp_as: 65001
  neighbors:
    - peer_as: 65002
      peer_ip: 10.0.0.2
    - peer_as: 65002
      peer_ip: 10.0.1.1
    - peer_as: 65003
      peer_ip: 10.0.0.1
    - peer_as: 65004
      peer_ip: 10.0.1.2

interfaces:
  "Ethernet0/1":
    ip: 10.0.0.3/29
    description: "IntercoLeft"
  "Ethernet0/2":
    ip: 10.0.1.3/29
    description: "IntercoRight"
  "Loopback1":
    ip: 100.64.1.1/32
    description: "BGP Loopback"
  "Loopback2":
    ip: 1.1.1.1/32
    description: "BGP Loopback"
