---
hostname: rt-cisco-2

bgp:
  bgp_as: 65004
  neighbors:
    - peer_as: 65002
      peer_ip: 10.0.1.1
    - peer_as: 65001
      peer_ip: 10.0.1.3

interfaces:
  "Ethernet0/1":
    ip: 10.0.1.2/29
    description: "IntercoLeft"
  "Loopback1":
    ip: 100.64.1.4/32
    description: "BGP Loopback"
  "Loopback2":
    ip: 4.4.4.4/32
    description: "BGP Loopback"


