---
hostname: rt-vyos-2

bgp:
  bgp_as: 65002
  neighbors:
    - peer_as: 65001
      peer_ip: 10.0.0.3

interfaces:
  "eth1":
    ip: 10.0.0.2/29
    description: "IntercoLeft"
  "eth2":
    ip: 10.0.1.1/29
    description: "IntercoRight"

loopback:
  "dum1":
    ip: 100.64.1.2/32
    description: "BGP_Loopback"
  "dum2":
    ip: 2.2.2.2/32
    description: "BGP_Loopback"

